DROP TABLE IF EXISTS STATS CASCADE;

CREATE TABLE IF NOT EXISTS STATS
(
    id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY UNIQUE,
    app     VARCHAR(255) NOT NULL,
    uri     VARCHAR(255) NOT NULL,
    ip      VARCHAR(255) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE
    );